name: New release end-user issue
description: Create a new issue for WordPress release end-user docs.
title: "[HelpHub]: "
labels: ["user documentation (HelpHub)", "[Status] To do"]
body:
- type: input
  attributes:
    label: Article URL
    description: "What is the article URL (if one exists)?"
    placeholder: "Article: <https://wordpress.org/documentation/article/...>"
    value: "Article:"
- type: dropdown
  attributes:
    label: Version update
    description: "Which version is this update for?"
    options: 
      - 6.4
      - 6.3
      - 6.2
      - 6.1
      - 6.0
- type: textarea
  attributes:
    label: Version updates
    description: "List all version updates."
    value: |
      - [ ] Title of Gutenberg issue/pull request with a link to it
      - [ ] Example: _Post comments form: Add spacing support. [45091](https://github.com/WordPress/gutenberg/pull/45091)_
      - [ ] 
      ...
    render: markdown
- type: checkboxes
  attributes:
    label: General updates
    description: "General updates."
    options: 
      - label: Make sure all screenshots are relevant to the latest version
      - label: Make sure videos, if any, are up to date
      - label: Add ALT tags for the images
      - label: Make sure the headings are in sentence case
      - label: Convert all reusable blocks to a ‘regular block’.
      - label: Update the changelog at the end of the article
- type: markdown
  attributes:
    value: |
      ## Notes
      1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
      2. Some of the PRs have great videos that can be added to the article
  
