# https://github.com/marketplace/actions/github-script
# https://github.com/orgs/community/discussions/25389#discussioncomment-3247738

name: Label and assign issues when commented
on: 
  issue_comment:
    types: [created, edited]

jobs:
        
  label_issues:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: console.log(context)
      - uses: actions/github-script@v6
        if: contains(github.event.comment.body, '/review')   # check the comment if it contains the keywords
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[Status] Review"]
            })
      - uses: actions/github-script@v6
        if: contains(github.event.issue.labels.*.name, '[Status] In progress') && contains(github.event.comment.body, '/review')  
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["[Status] In progress"]
            })
      - uses: actions/github-script@v6
        if: contains(github.event.issue.labels.*.name, '[Status] To do') && contains(github.event.comment.body, '/review')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["[Status] To do"]
            })
      - uses: actions/github-script@v6
        if: contains(github.event.issue.labels.*.name, '[Status] Done') && contains(github.event.comment.body, '/review')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["[Status] Done"]
            })

  assign_issue:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
#       - uses: actions/github-script@v6
#         with:
#           script: console.log(context)
      - uses: actions/github-script@v6
        if: contains(github.event.comment.body, '/assign')   # check the comment if it contains the keywords
        with:
          script: console.log(github.event.comment)
          
  
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
      
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
        
  #   - name: Install dependencies
  #     run: npm install
        
  #   - name: Run assign-issue.js
  #     run: node .github/scripts/assign-issue.js
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
