name: Notify team based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        # https://github.com/marketplace/actions/issue-label-notifier
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
             # The Team
             # https://make.wordpress.org/docs/handbook/the-team/
             recipients: |
                  block editor=@femkreations
                  has-screenshots=@femkreations @atachibana
                  user documentation=@femkreations @atachibana
                  plugins=@theMikeD
                  themes=@kafleg @carolinan @TeBenachi
                  code reference=@stevenlinx
                  external links=@zzap
                  apis=@zzap
                  advanced administration=@javiercasares
                  tutorial review=@femkreations
                  [Status] Review=@docs-reviewers
